package com.alimesa.ordenpedido.librerias.vista.beans;

public enum NombresEtiquetas {
	TITULOPAGINA, TABLAVACIA, DESCRIPCIONPAGINA, AYUDAPAGINA, TAB, CABECERATABLA, CABECERADIALOGO, CABECERAPANELDIALOGO, MENSAJE_TRANSACCION
}